version: '3.8'

services:
  gateway-server:
    container_name: gateway-server
    build:
      context: ./gateway-server
      dockerfile: Dockerfile.dev
    volumes:
      - ./gateway-server:/app
      - /app/node_modules
    ports:
      - '3000:3000'

  auth-server:
    container_name: auth-server
    build:
      context: ./auth-server
      dockerfile: Dockerfile.dev
    volumes:
      - ./auth-server:/app
      - /app/node_modules
    ports:
      - '3001:3000'
    environment:
      - MONGO_URI=mongodb://auth-mongo:27017/auth-db
    networks:
      - auth-network
    depends_on:
      - auth-mongo

  auth-mongo:
    image: mongo:8.0
    container_name: auth-mongo
    ports:
      - "27017:27017" # 로컬 접근용
    volumes:
      - auth-mongo-data:/data/db
    networks:
      - auth-network

  event-server:
    container_name: event-server
    build:
      context: ./event-server
      dockerfile: Dockerfile.dev
    volumes:
      - ./event-server:/app
      - /app/node_modules
    ports:
      - '3002:3000'
    environment:
      - MONGO_URI=mongodb://event-mongo:27017/event-db
    networks:
      - event-network
    depends_on:
      - event-mongo

  event-mongo:
    image: mongo:8.0
    container_name: event-mongo
    volumes:
      - event-mongo-data:/data/db
    networks:
      - event-network

volumes:
  auth-mongo-data:
  event-mongo-data:

networks:
  auth-network:
  event-network: